sudo: required
language: python
env:
  - TASK_VERSION=v2.4.0
  - TASK_VERSION=v2.4.1
  - TASK_VERSION=v2.4.2
  - TASK_VERSION=v2.4.3
  - TASK_VERSION=v2.4.4
  - TASK_VERSION=v2.5.0
  - TASK_VERSION=v2.5.1
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker
before_install:
  # Setup virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Install coverage dependencies
  - pip install coverage coveralls
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - docker-compose build --build-arg TASK_VERSION=$TASK_VERSION tests
script:
  - xhost +local:root
  - make test
after_success:
  - ls /tmp/taskwiki-coverage
  - mv /tmp/taskwiki-coverage/.coverage.* . || echo ok
  - coverage combine
  - coverage report
  - coveralls
